### ISSUE TITLE
Blockquotes Component

### ISSUE THREAD

**Issue by ichim-david** [eea/volto-eea-design-system#38]
Component demo:
https://eea.github.io/volto-kitkat-frontend/?path=/story/components-blockquote--default

- [x] Follow Semantic UI conventions / constructs even for new components but use .eea parent class
ex:

.ui .card .author

If we have **Blockquote** component which Semantic UI doesn't have them we will use:

.eea .blockquote
.eea .blockquote .quote
.eea .blockquote .author

It's more specific and verbose than **.eea-blockquote-author** but it follows the way Semantic UI is styled and it will bring
some component encapsulation
- [x] Since it's a new component you need to define variables that can be set per component variable
  ex:
   https://github.com/eea/volto-eea-design-system/blob/develop-itml/theme/themes/eea/extras/custom.overrides#L182
  ```less
   .eea .blockquote {
    border-left: @blockquoteBorderLeft; 
  }
  ```
  then in **custom.variables**
  ```less
  @blockquoteBorderLeft: 10px solid @secondaryColor;
  ```
 Like this is someone wants a 5px solid @greenColor for the blockquote
 then can in their site theme add **custom.variables**
 @blockquoteBorderLeft: 5px solid @greenColor;
And the final CSS output will be without any overrides:
 ```css
 .eea .blockquote {
    border-left: 5px solid green; 
  }
```
- [x] Same way for child elements 
https://github.com/eea/volto-eea-design-system/blob/develop-itml/theme/themes/eea/extras/custom.overrides#L192
  ```less 
  @blockquoteAuthorMarginTop: @relative16px;
  .eea blockquote .author {
      margin-top: @blockquoteAuthorMarginTop;
      font-weight: bold;
  }
  ```

https://github.com/eea/volto-eea-design-system/blob/develop-itml/theme/themes/eea/extras/blockquote.less#L20

- [x] please use full variable reference @quoteFontSize as @quoteSize could be misleading to a width instead of font size
- [ ] Check docusaurus documentation, the design doesn't clip the text after 80 characters as the documentation says that
  the quote shouldn't go over the limit
